[package]
name = "tfile-rs"
version = "0.3.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"  # Универсальная цветная библиотека
atty = "0.2"        # Для определения поддержки цветов
clap = { version = "4.0", features = ["derive"] }