[package]
name = "tfile-rs"
version = "1.0.2"
edition = "2021"
license = "MIT"

[[bin]]
name = "tfile"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }  # Для аргументов командной строки
termcolor = "1.4"
